# import packages

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels
import scipy
from scipy import stats
from scipy.stats import boxcox
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multicomp import MultiComparison
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.proportion import proportions_chisquare
from sklearn.metrics import ConfusionMatrixDisplay

# read in data

In [2]:
shelterSplitByMonth=pd.read_csv("C:/Users/hazre/OneDrive/OneNote/GitHub/Final-Project/shelterSplitByMonth.csv")

In [3]:
shelterSplitByMonth.head()

,id,intakereason,animalname,breedname,basecolour,speciesname,animalage,sexname,movementtype,intakeDate,movementDate,CatAgeGroup,DogAgeGroup,movementMonth,movementDay,movementYear,intakeMonth,intakeDay,intakeYear
0,15801,Moving,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,11 years 8 months.,Female,Adoption,11/28/2009,05/13/2017,Senior,Senior,5,13,2017,11,28,2009
1,15932,Moving,Gonzo,German Shepherd Dog/Mix,Tan,Dog,10 years 9 months.,Male,Adoption,12/08/2009,04/24/2017,Mature,Senior,4,24,2017,12,8,2009
2,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Adoption,08/10/2012,04/15/2017,Mature,Mature,4,15,2017,8,10,2012
3,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Reclaimed,08/10/2012,02/29/2020,Mature,Mature,2,29,2020,8,10,2012
4,30812,Abandoned,Pretty Girl,Domestic Short Hair,Dilute tortoiseshell,Cat,10 years 6 months.,Female,Foster,01/11/2013,04/18/2017,Mature,Senior,4,18,2017,1,11,2013

## recode intakeMonth to reflect month names

In [4]:
shelterSplitByMonth.intakeMonth.value_counts()

6     2193
7     2152
5     2068
9     1935
8     1812
10    1762
4     1300
11    1242
3     1037
12    1014
1      902
2      891
Name: intakeMonth, dtype: int64

In [5]:
def intakeMonthR (series):
    if series == 1:
        return "January"
    if series -- 2:
        return "February"
    if series == 3:
        return "March"
    if series == 4:
        return "April"
    if series == 5:
        return "May"
    if series == 6:
        return "June"
    if series == 7:
        return "July"
    if series == 8:
        return "August"
    if series == 9:
        return "September"
    if series == 10:
        return "October"
    if series == 11:
        return "November"
    if series == 12:
        return December
shelterSplitByMonth["intakeMonthR"]= shelterSplitByMonth["intakeMonth"].apply(intakeMonthR)

In [6]:
shelterSplitByMonth.head()

,id,intakereason,animalname,breedname,basecolour,speciesname,animalage,sexname,movementtype,intakeDate,movementDate,CatAgeGroup,DogAgeGroup,movementMonth,movementDay,movementYear,intakeMonth,intakeDay,intakeYear,intakeMonthR
0,15801,Moving,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,11 years 8 months.,Female,Adoption,11/28/2009,05/13/2017,Senior,Senior,5,13,2017,11,28,2009,February
1,15932,Moving,Gonzo,German Shepherd Dog/Mix,Tan,Dog,10 years 9 months.,Male,Adoption,12/08/2009,04/24/2017,Mature,Senior,4,24,2017,12,8,2009,February
2,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Adoption,08/10/2012,04/15/2017,Mature,Mature,4,15,2017,8,10,2012,February
3,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Reclaimed,08/10/2012,02/29/2020,Mature,Mature,2,29,2020,8,10,2012,February
4,30812,Abandoned,Pretty Girl,Domestic Short Hair,Dilute tortoiseshell,Cat,10 years 6 months.,Female,Foster,01/11/2013,04/18/2017,Mature,Senior,4,18,2017,1,11,2013,January