In [1]:
import pandas as pd

In [2]:
shelter = pd.read_csv(r'C:\Users\ardit\Desktop\python_course\Final Project\animalShelter.csv')
pd.set_option('display.max_columns', None)
shelter.head()

,id,intakereason,animalname,breedname,basecolour,speciesname,animalage,sexname,movementtype,intakeDate,movementDate,CatAgeGroup,DogAgeGroup,movementMonth,movementDay,movementYear,intakeMonth,intakeDay,intakeYear,intakeMonthR
0,15801,Moving,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,11 years 8 months.,Female,Adoption,11/28/2009,05/13/2017,Senior,Senior,5,13,2017,11,28,2009,February
1,15932,Moving,Gonzo,German Shepherd Dog/Mix,Tan,Dog,10 years 9 months.,Male,Adoption,12/08/2009,04/24/2017,Mature,Senior,4,24,2017,12,8,2009,February
2,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Adoption,08/10/2012,04/15/2017,Mature,Mature,4,15,2017,8,10,2012,February
3,28859,Abandoned,Maggie,Shep Mix/Siberian Husky,Various,Dog,8 years 1 month.,Female,Reclaimed,08/10/2012,02/29/2020,Mature,Mature,2,29,2020,8,10,2012,February
4,30812,Abandoned,Pretty Girl,Domestic Short Hair,Dilute tortoiseshell,Cat,10 years 6 months.,Female,Foster,01/11/2013,04/18/2017,Mature,Senior,4,18,2017,1,11,2013,January

In [3]:
shelter.drop(['animalname', 'basecolour', 'animalage', 'intakeMonthR'], axis=1, inplace=True)

In [4]:
shelter.head()

,id,intakereason,breedname,speciesname,sexname,movementtype,intakeDate,movementDate,CatAgeGroup,DogAgeGroup,movementMonth,movementDay,movementYear,intakeMonth,intakeDay,intakeYear
0,15801,Moving,Domestic Short Hair,Cat,Female,Adoption,11/28/2009,05/13/2017,Senior,Senior,5,13,2017,11,28,2009
1,15932,Moving,German Shepherd Dog/Mix,Dog,Male,Adoption,12/08/2009,04/24/2017,Mature,Senior,4,24,2017,12,8,2009
2,28859,Abandoned,Shep Mix/Siberian Husky,Dog,Female,Adoption,08/10/2012,04/15/2017,Mature,Mature,4,15,2017,8,10,2012
3,28859,Abandoned,Shep Mix/Siberian Husky,Dog,Female,Reclaimed,08/10/2012,02/29/2020,Mature,Mature,2,29,2020,8,10,2012
4,30812,Abandoned,Domestic Short Hair,Cat,Female,Foster,01/11/2013,04/18/2017,Mature,Senior,4,18,2017,1,11,2013

In [5]:
shelter1 = shelter[(shelter.CatAgeGroup != "Unknown") & (shelter.DogAgeGroup != "Unknown") & (shelter.sexname != "Unknown")]
shelter1.head()

,id,intakereason,breedname,speciesname,sexname,movementtype,intakeDate,movementDate,CatAgeGroup,DogAgeGroup,movementMonth,movementDay,movementYear,intakeMonth,intakeDay,intakeYear
0,15801,Moving,Domestic Short Hair,Cat,Female,Adoption,11/28/2009,05/13/2017,Senior,Senior,5,13,2017,11,28,2009
1,15932,Moving,German Shepherd Dog/Mix,Dog,Male,Adoption,12/08/2009,04/24/2017,Mature,Senior,4,24,2017,12,8,2009
2,28859,Abandoned,Shep Mix/Siberian Husky,Dog,Female,Adoption,08/10/2012,04/15/2017,Mature,Mature,4,15,2017,8,10,2012
3,28859,Abandoned,Shep Mix/Siberian Husky,Dog,Female,Reclaimed,08/10/2012,02/29/2020,Mature,Mature,2,29,2020,8,10,2012
4,30812,Abandoned,Domestic Short Hair,Cat,Female,Foster,01/11/2013,04/18/2017,Mature,Senior,4,18,2017,1,11,2013

In [7]:
dictionary = { 'intakereason':
{ "Owner Died": "Owner Deceased" }}
shelter1.replace(dictionary, inplace=True)

In [8]:
shelter1.to_csv(r'C:\Users\ardit\Desktop\python_course\Final Project\shelterDates.csv', index = False)